import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Dark Theme
        'on-error': '#690005',
        'on-secondary': '#213145',
        'on-primary': '#002e6a',
        'surface-container-lowest': '#0b0e15',
        'on-tertiary-container': '#461f00',
        'primary': '#adc6ff',
        'surface-bright': '#363941',
        'surface': '#10131a',
        'on-primary-container': '#00285d',
        'on-primary-fixed': '#001a42',
        'secondary-container': '#3a4a5f',
        'surface-variant': '#32353c',
        'on-surface': '#e1e2ec',
        'background': '#10131a',
        'on-secondary-container': '#a9bad3',
        'outline': '#8c909f',
        'on-secondary-fixed': '#0b1c30',
        'tertiary-fixed': '#ffdcc6',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed-variant': '#004395',
        'error-container': '#93000a',
        'on-tertiary': '#502400',
        'tertiary': '#ffb786',
        'secondary': '#b7c8e1',
        'outline-variant': '#424754',
        'primary-fixed': '#d8e2ff',
        'surface-container-highest': '#32353c',
        'surface-container-low': '#191b23',
        'inverse-surface': '#e1e2ec',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#e1e2ec',
        'inverse-primary': '#005ac2',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-dim': '#10131a',
        'error': '#ffb4ab',
        'secondary-fixed': '#d3e4fe',
        'on-secondary-fixed-variant': '#38485d',
        'inverse-on-surface': '#2e3038',
        'on-tertiary-fixed': '#311400',
        'tertiary-container': '#df7412',
        'surface-tint': '#adc6ff',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#272a31',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed-variant': '#723600',
        'primary-container': '#4d8eff',
        'surface-container': '#1d2027',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'base': '4px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        'margin': '24px',
        'sidebar-width': '260px',
        'gutter': '16px',
      },
      fontFamily: {
        'body-lg': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'headline-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'headline-lg': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'label-mono': ['var(--font-jetbrains)', 'monospace'],
        'code-block': ['var(--font-jetbrains)', 'monospace'],
        'headline-xl': ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-mono': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'code-block': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
export default config
