insert into datasets (
    id,
    name,
    description,
    dataset_type,
    status,
    size_bytes,
    item_count,
    label_status,
    tags,
    storage_path,
    created_by,
    source_payload
) values
    (
        'ds_001',
        'Iris Sample Dataset',
        'Iris sample CSV migrated from the legacy workspace storage.',
        'tabular',
        'ready',
        104857600,
        150,
        'labeled',
        '["tabular", "classification", "migration"]'::jsonb,
        'migration/server/datasets/ds_001/iris_sample.csv',
        'migration',
        '{"class_count": 3}'::jsonb
    ),
    (
        'ds_002',
        'YOLOv8 Custom Dataset',
        'Object detection sample dataset migrated from MinIO.',
        'image',
        'ready',
        52428800,
        5000,
        'labeled',
        '["vision", "object-detection", "migration"]'::jsonb,
        'migration/server/datasets/ds_002/sample.csv',
        'migration',
        '{"class_count": 8}'::jsonb
    ),
    (
        'ds_003',
        'Sentiment Tweets Dataset',
        'Text classification sample dataset migrated from MinIO.',
        'text',
        'ready',
        18874368,
        25000,
        'labeled',
        '["nlp", "sentiment", "migration"]'::jsonb,
        'migration/server/datasets/ds_003/tweets_sample.txt',
        'migration',
        '{"class_count": 3}'::jsonb
    ),
    (
        'ds_004',
        'Audio Manifest Dataset',
        'Audio manifest sample dataset migrated from MinIO.',
        'audio',
        'ready',
        73400320,
        1200,
        'processing',
        '["audio", "manifest", "migration"]'::jsonb,
        'migration/server/datasets/ds_004/audio_manifest.csv',
        'migration',
        '{"class_count": 10}'::jsonb
    ),
    (
        'ds_005',
        'Video Manifest Dataset',
        'Video manifest sample dataset migrated from MinIO.',
        'video',
        'ready',
        188743680,
        320,
        'processing',
        '["video", "manifest", "migration"]'::jsonb,
        'migration/server/datasets/ds_005/video_manifest.csv',
        'migration',
        '{"class_count": 6}'::jsonb
    ),
    (
        'iris_dataset',
        'Iris Dataset',
        'Classic Iris CSV dataset migrated from MinIO.',
        'tabular',
        'ready',
        16384,
        150,
        'labeled',
        '["tabular", "classification", "iris"]'::jsonb,
        'migration/server/datasets/iris_dataset/iris.csv',
        'migration',
        '{"class_count": 3}'::jsonb
    ),
    (
        'coco_2017_detection',
        'COCO 2017 Detection Sample',
        'COCO detection sample files migrated from MinIO.',
        'image',
        'ready',
        3221225472,
        120000,
        'labeled',
        '["vision", "detection", "coco"]'::jsonb,
        'migration/server/datasets/coco_2017_detection/sample_0001.jpg',
        'migration',
        '{"class_count": 80}'::jsonb
    )
on conflict (id) do update set
    name = excluded.name,
    description = excluded.description,
    dataset_type = excluded.dataset_type,
    status = excluded.status,
    size_bytes = excluded.size_bytes,
    item_count = excluded.item_count,
    label_status = excluded.label_status,
    tags = excluded.tags,
    storage_path = excluded.storage_path,
    created_by = excluded.created_by,
    source_payload = excluded.source_payload,
    updated_at = now();

update models
set storage_path = 'migration/server/models/model_ee2d8dd13626_sample-model.onnx',
    updated_at = now()
where id = 'model_ee2d8dd13626';
