CREATE SCHEMA IF NOT EXISTS mlops;

CREATE TABLE users (
	id UUID NOT NULL, 
	email TEXT, 
	full_name TEXT, 
	password_hash TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE git_accounts (
	user_id UUID NOT NULL, 
	provider git_provider_type NOT NULL, 
	username VARCHAR(255) NOT NULL, 
	access_token VARCHAR(1024) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE git_sync_preferences (
	user_id UUID NOT NULL, 
	auto_sync_experiments BOOLEAN DEFAULT 'true' NOT NULL, 
	commit_checkpoints BOOLEAN DEFAULT 'false' NOT NULL, 
	create_pr_on_completion BOOLEAN DEFAULT 'true' NOT NULL, 
	sync_interval INTEGER DEFAULT '15' NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE mlops.audit_logs (
	id BIGSERIAL NOT NULL, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_id UUID NOT NULL, 
	action VARCHAR(50) NOT NULL, 
	actor_id UUID NOT NULL, 
	actor_role VARCHAR(50), 
	old_value JSONB, 
	new_value JSONB, 
	metadata JSONB, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(actor_id) REFERENCES users (id)
);
CREATE TABLE mlops.dvc_profiles (
	id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	scope mlops_dvc_profile_scope DEFAULT 'global' NOT NULL, 
	scope_id VARCHAR(64), 
	repo_mode mlops_dvc_profile_repo_mode DEFAULT 'managed_git' NOT NULL, 
	git_repo_url VARCHAR(500), 
	git_branch VARCHAR(100) DEFAULT 'main' NOT NULL, 
	repo_path VARCHAR(500) NOT NULL, 
	remote_name VARCHAR(100) DEFAULT 'minio' NOT NULL, 
	remote_url VARCHAR(500), 
	endpoint_url VARCHAR(500), 
	is_default BOOLEAN DEFAULT 'false' NOT NULL, 
	status mlops_dvc_profile_status DEFAULT 'ready' NOT NULL, 
	status_message TEXT, 
	git_ssh_url TEXT, 
	git_repo_owner VARCHAR(255), 
	git_repo_name VARCHAR(255), 
	github_installation_id BIGINT, 
	github_deploy_key_id BIGINT, 
	ssh_key_encrypted BYTEA, 
	ssh_public_key TEXT, 
	created_by UUID, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_mlops_dvc_profiles_name_scope UNIQUE (name, scope, scope_id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
CREATE TABLE mlops.experiments (
	id UUID NOT NULL, 
	mlflow_experiment_id BIGINT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	owner_id UUID NOT NULL, 
	team_id UUID, 
	tags JSONB DEFAULT '{}'::jsonb NOT NULL, 
	artifact_location VARCHAR(500), 
	lifecycle_stage mlops_experiment_lifecycle DEFAULT 'active' NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (mlflow_experiment_id), 
	FOREIGN KEY(owner_id) REFERENCES users (id)
);
CREATE TABLE storage_connections (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	provider VARCHAR(50) NOT NULL, 
	remote_name VARCHAR(100) NOT NULL, 
	config_path TEXT NOT NULL, 
	display_name VARCHAR(255) NOT NULL, 
	encrypted_credentials TEXT, 
	status VARCHAR(50) DEFAULT 'connected' NOT NULL, 
	is_default BOOLEAN DEFAULT 'false' NOT NULL, 
	last_sync_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE workspaces (
	id VARCHAR(20) NOT NULL, 
	user_id UUID NOT NULL, 
	name VARCHAR(255), 
	status workspace_status DEFAULT 'READY' NOT NULL, 
	tier VARCHAR(30) NOT NULL, 
	k8s_namespace VARCHAR(63), 
	k8s_pod_name VARCHAR(63), 
	pod_ip VARCHAR(45), 
	access_url TEXT, 
	jupyter_token_hash VARCHAR(64), 
	dataset_ids JSONB DEFAULT '[]'::jsonb NOT NULL, 
	model_ids JSONB DEFAULT '[]'::jsonb NOT NULL, 
	environment_config JSONB DEFAULT '{}'::jsonb NOT NULL, 
	resource_config JSONB DEFAULT '{}'::jsonb NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE, 
	stopped_at TIMESTAMP WITH TIME ZONE, 
	last_heartbeat TIMESTAMP WITH TIME ZONE, 
	last_kernel_activity TIMESTAMP WITH TIME ZONE, 
	auto_kill_at TIMESTAMP WITH TIME ZONE, 
	error_message TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TABLE external_runtime_sessions (
	id UUID NOT NULL, 
	workspace_id VARCHAR(20) NOT NULL, 
	user_id UUID NOT NULL, 
	provider VARCHAR(30) DEFAULT 'google_colab' NOT NULL, 
	status runtime_session_status DEFAULT 'CREATED' NOT NULL, 
	token_jti VARCHAR(64), 
	capabilities JSONB DEFAULT '[]'::jsonb NOT NULL, 
	connected_at TIMESTAMP WITH TIME ZONE, 
	last_heartbeat_at TIMESTAMP WITH TIME ZONE, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	revoke_reason TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (token_jti)
);
CREATE TABLE git_repositories (
	git_account_id UUID NOT NULL, 
	repo_name VARCHAR(255) NOT NULL, 
	repo_url VARCHAR(1024) NOT NULL, 
	is_private BOOLEAN DEFAULT 'false' NOT NULL, 
	is_tracked BOOLEAN DEFAULT 'false' NOT NULL, 
	tracked_branch VARCHAR(255) DEFAULT 'main' NOT NULL, 
	last_sync_time TIMESTAMP WITH TIME ZONE, 
	sync_status VARCHAR(50), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(git_account_id) REFERENCES git_accounts (id) ON DELETE CASCADE
);
CREATE TABLE mlops.datasets (
	id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	type mlops_dataset_type NOT NULL, 
	owner_id UUID NOT NULL, 
	team_id UUID, 
	dvc_profile_id UUID, 
	dvc_repo_url VARCHAR(500), 
	storage_path VARCHAR(500), 
	tags JSONB DEFAULT '[]'::jsonb NOT NULL, 
	status mlops_dataset_status DEFAULT 'active' NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	FOREIGN KEY(owner_id) REFERENCES users (id), 
	FOREIGN KEY(dvc_profile_id) REFERENCES mlops.dvc_profiles (id) ON DELETE SET NULL
);
CREATE TABLE workspace_events (
	id BIGSERIAL NOT NULL, 
	workspace_id VARCHAR(20) NOT NULL, 
	event_type VARCHAR(50) NOT NULL, 
	actor VARCHAR(50) NOT NULL, 
	details JSONB DEFAULT '{}'::jsonb NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);
CREATE TABLE mlops.dataset_versions (
	id UUID NOT NULL, 
	dataset_id UUID NOT NULL, 
	version VARCHAR(50) NOT NULL, 
	dvc_md5 VARCHAR(64), 
	dvc_commit VARCHAR(40), 
	dvc_profile_id UUID, 
	git_tag VARCHAR(100), 
	size_bytes BIGINT, 
	item_count INTEGER, 
	schema_snapshot JSONB, 
	split_info JSONB, 
	storage_path VARCHAR(500), 
	metadata_uri VARCHAR(500), 
	validation_report_uri VARCHAR(500), 
	validation_status VARCHAR(30), 
	validation_summary JSONB, 
	metadata_snapshot JSONB, 
	format VARCHAR(50), 
	task_type VARCHAR(50), 
	created_by UUID NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	changelog TEXT, 
	is_latest BOOLEAN DEFAULT 'false' NOT NULL, 
	status mlops_dataset_version_status DEFAULT 'draft' NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_mlops_dataset_versions_dataset_version UNIQUE (dataset_id, version), 
	FOREIGN KEY(dataset_id) REFERENCES mlops.datasets (id) ON DELETE CASCADE, 
	FOREIGN KEY(dvc_profile_id) REFERENCES mlops.dvc_profiles (id) ON DELETE SET NULL, 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
CREATE TABLE mlops.runs (
	id UUID NOT NULL, 
	mlflow_run_id VARCHAR(32) NOT NULL, 
	experiment_id UUID NOT NULL, 
	workspace_id VARCHAR(20), 
	runtime_session_id UUID, 
	name VARCHAR(255), 
	status mlops_run_status NOT NULL, 
	start_time TIMESTAMP WITHOUT TIME ZONE, 
	end_time TIMESTAMP WITHOUT TIME ZONE, 
	artifact_uri VARCHAR(500), 
	source_type mlops_run_source_type, 
	source_name VARCHAR(500), 
	git_commit VARCHAR(40), 
	user_id UUID NOT NULL, 
	metrics_snapshot JSONB, 
	params_snapshot JSONB, 
	tags_snapshot JSONB, 
	dvc_dataset_version_id UUID, 
	dvc_md5 VARCHAR(64), 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (mlflow_run_id), 
	FOREIGN KEY(experiment_id) REFERENCES mlops.experiments (id), 
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE SET NULL, 
	FOREIGN KEY(runtime_session_id) REFERENCES external_runtime_sessions (id) ON DELETE SET NULL, 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(dvc_dataset_version_id) REFERENCES mlops.dataset_versions (id)
);
CREATE TABLE workspace_datasets (
	id SERIAL NOT NULL, 
	workspace_id VARCHAR(20) NOT NULL, 
	dataset_id UUID NOT NULL, 
	mount_path VARCHAR(255) NOT NULL, 
	mounted_by VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, 
	FOREIGN KEY(dataset_id) REFERENCES mlops.dataset_versions (id) ON DELETE CASCADE
);
CREATE TABLE mlops.model_versions (
	id UUID NOT NULL, 
	mlflow_name VARCHAR(255) NOT NULL, 
	mlflow_version INTEGER NOT NULL, 
	run_id UUID NOT NULL, 
	description TEXT, 
	stage mlops_model_stage DEFAULT 'None' NOT NULL, 
	status mlops_model_status DEFAULT 'PENDING_REGISTRATION' NOT NULL, 
	source VARCHAR(500), 
	framework VARCHAR(50), 
	task_type VARCHAR(50), 
	size_bytes BIGINT, 
	metrics JSONB, 
	tags JSONB, 
	approved_by UUID, 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	created_by UUID NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_mlops_model_versions_mlflow_name_version UNIQUE (mlflow_name, mlflow_version), 
	CONSTRAINT ck_mlops_model_versions_prod_requires_approval CHECK ((stage <> 'Production') OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)), 
	FOREIGN KEY(run_id) REFERENCES mlops.runs (id), 
	FOREIGN KEY(approved_by) REFERENCES users (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
CREATE TABLE mlops.run_logs (
	id BIGSERIAL NOT NULL, 
	run_id UUID NOT NULL, 
	runtime_session_id UUID NOT NULL, 
	level VARCHAR(10) NOT NULL, 
	message TEXT NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(run_id) REFERENCES mlops.runs (id) ON DELETE CASCADE, 
	FOREIGN KEY(runtime_session_id) REFERENCES external_runtime_sessions (id) ON DELETE CASCADE
);
CREATE TABLE mlops.approval_requests (
	id UUID NOT NULL, 
	model_version_id UUID NOT NULL, 
	requested_by UUID NOT NULL, 
	requested_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	target_stage mlops_approval_target_stage NOT NULL, 
	status mlops_approval_status DEFAULT 'pending' NOT NULL, 
	reviewer_id UUID, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	review_note TEXT, 
	auto_approved BOOLEAN DEFAULT 'false' NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(model_version_id) REFERENCES mlops.model_versions (id) ON DELETE CASCADE, 
	FOREIGN KEY(requested_by) REFERENCES users (id), 
	FOREIGN KEY(reviewer_id) REFERENCES users (id)
);
CREATE TABLE mlops.model_dataset_links (
	id UUID NOT NULL, 
	model_version_id UUID NOT NULL, 
	dataset_version_id UUID NOT NULL, 
	link_type mlops_link_type NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	created_by UUID NOT NULL, 
	notes TEXT, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_mlops_model_dataset_links_model_dataset_type UNIQUE (model_version_id, dataset_version_id, link_type), 
	FOREIGN KEY(model_version_id) REFERENCES mlops.model_versions (id) ON DELETE CASCADE, 
	FOREIGN KEY(dataset_version_id) REFERENCES mlops.dataset_versions (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
CREATE TABLE workspace_models (
	id SERIAL NOT NULL, 
	workspace_id VARCHAR(20) NOT NULL, 
	model_id UUID NOT NULL, 
	mount_path VARCHAR(255) NOT NULL, 
	mounted_by VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, 
	FOREIGN KEY(model_id) REFERENCES mlops.model_versions (id) ON DELETE CASCADE
);
