"""Add git tracking and sync preferences

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10ff4a5a9b38'
down_revision: Union[str, None] = '6a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_sync_preferences',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('auto_sync_experiments', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('commit_checkpoints', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('create_pr_on_completion', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_interval', sa.Integer(), server_default='15', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('git_repositories', sa.Column('is_tracked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('git_repositories', sa.Column('tracked_branch', sa.String(length=255), server_default='main', nullable=False))
    op.add_column('git_repositories', sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('git_repositories', sa.Column('sync_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('git_repositories', 'sync_status')
    op.drop_column('git_repositories', 'last_sync_time')
    op.drop_column('git_repositories', 'tracked_branch')
    op.drop_column('git_repositories', 'is_tracked')
    op.drop_table('git_sync_preferences')
    # ### end Alembic commands ###
