"""cleanup_colab_workspace_schema

Revision ID: 42b5735fc9fe
Revises: c14bbe97f431
Create Date: 2026-07-13 09:05:20.399100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b5735fc9fe'
down_revision: Union[str, None] = 'c14bbe97f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('storage_providers')
    op.add_column('workspaces', sa.Column('passcode_hash', sa.String(length=64), nullable=True))
    op.drop_index('ix_workspaces_k8s_namespace_lookup', table_name='workspaces')
    op.drop_column('workspaces', 'jupyter_token_hash')
    op.drop_column('workspaces', 'pod_ip')
    op.drop_column('workspaces', 'k8s_pod_name')
    op.drop_column('workspaces', 'environment_config')
    op.drop_column('workspaces', 'resource_config')
    op.drop_column('workspaces', 'k8s_namespace')
    op.drop_column('workspaces', 'tier')
    # Drop partial index that references the old enum type before renaming
    op.drop_index('ix_workspaces_status_auto_kill_at_running', table_name='workspaces')
    op.execute("ALTER TYPE workspace_status RENAME TO workspace_status_old")
    op.execute("CREATE TYPE workspace_status AS ENUM ('READY', 'RUNNING', 'STOPPED', 'ERROR')")
    op.execute("ALTER TABLE workspaces ALTER COLUMN status DROP DEFAULT")
    op.execute("""
        ALTER TABLE workspaces
        ALTER COLUMN status TYPE workspace_status
        USING status::text::workspace_status
    """)
    op.execute("ALTER TABLE workspaces ALTER COLUMN status SET DEFAULT 'READY'::workspace_status")
    op.execute("DROP TYPE workspace_status_old")
    # Recreate the partial index with the new enum type
    op.create_index(
        'ix_workspaces_status_auto_kill_at_running',
        'workspaces',
        ['status', 'auto_kill_at'],
        postgresql_where=sa.text("status = 'RUNNING'::workspace_status"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('k8s_namespace', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('resource_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('environment_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('k8s_pod_name', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('pod_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('jupyter_token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_workspaces_k8s_namespace_lookup', 'workspaces', ['k8s_namespace'], unique=False)
    op.drop_column('workspaces', 'passcode_hash')
    op.create_table('storage_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('minio', 's3', 'gdrive', name='storage_provider_type'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='storage_providers_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='storage_providers_pkey'),
    sa.UniqueConstraint('name', name='storage_providers_name_key')
    )
    op.drop_table('model_dataset_links', schema='mlops')
    op.drop_index('ix_mlops_approval_requests_model_version_status', table_name='approval_requests', schema='mlops')
    op.drop_table('approval_requests', schema='mlops')
    op.drop_index('ix_mlops_run_logs_run_created', table_name='run_logs', schema='mlops')
    op.drop_table('run_logs', schema='mlops')
    op.drop_index('ix_mlops_model_versions_stage', table_name='model_versions', schema='mlops')
    op.drop_table('model_versions', schema='mlops')
    op.drop_index('ix_mlops_runs_dvc_dataset_version_id', table_name='runs', schema='mlops')
    op.drop_table('runs', schema='mlops')
    op.drop_index('ix_mlops_dataset_versions_dvc_md5', table_name='dataset_versions', schema='mlops')
    op.drop_index('ix_mlops_dataset_versions_dvc_commit', table_name='dataset_versions', schema='mlops')
    op.drop_table('dataset_versions', schema='mlops')
    op.drop_table('datasets', schema='mlops')
    op.drop_table('experiments', schema='mlops')
    op.drop_index('ix_mlops_dvc_profiles_scope', table_name='dvc_profiles', schema='mlops')
    op.drop_table('dvc_profiles', schema='mlops')
    op.drop_index('ix_mlops_audit_logs_entity_entity_id_created', table_name='audit_logs', schema='mlops')
    op.drop_table('audit_logs', schema='mlops')
    # ### end Alembic commands ###
