"""add_is_default_to_storage_connection

Revision ID: c14bbe97f431
Revises: 5e23d17f8b5b
Create Date: 2026-06-29 06:38:10.804168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14bbe97f431'
down_revision: Union[str, None] = '5e23d17f8b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_connections', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_connections', 'is_default')
    # ### end Alembic commands ###
