"""create workspace assets tables

Revision ID: f5e49ed73434
Revises: c14bbe97f431
Create Date: 2026-07-02 04:16:54.169074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e49ed73434'
down_revision: Union[str, None] = 'c14bbe97f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mlops'
    )
    op.create_index('ix_mlops_audit_logs_entity_entity_id_created', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False, schema='mlops')
    op.create_table('dvc_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Enum('global', 'team', 'user', 'workspace', name='mlops_dvc_profile_scope'), server_default='global', nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=True),
    sa.Column('repo_mode', sa.Enum('managed_git', 'existing_path', name='mlops_dvc_profile_repo_mode'), server_default='managed_git', nullable=False),
    sa.Column('git_repo_url', sa.String(length=500), nullable=True),
    sa.Column('git_branch', sa.String(length=100), server_default='main', nullable=False),
    sa.Column('repo_path', sa.String(length=500), nullable=False),
    sa.Column('remote_name', sa.String(length=100), server_default='minio', nullable=False),
    sa.Column('remote_url', sa.String(length=500), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('ready', 'inactive', 'error', 'archived', 'pending_oauth', 'pending_repo_selection', 'active', name='mlops_dvc_profile_status'), server_default='ready', nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('git_ssh_url', sa.Text(), nullable=True),
    sa.Column('git_repo_owner', sa.String(length=255), nullable=True),
    sa.Column('git_repo_name', sa.String(length=255), nullable=True),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=True),
    sa.Column('github_deploy_key_id', sa.BigInteger(), nullable=True),
    sa.Column('ssh_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('ssh_public_key', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', 'scope_id', name='uq_mlops_dvc_profiles_name_scope'),
    schema='mlops'
    )
    op.create_index('ix_mlops_dvc_profiles_scope', 'dvc_profiles', ['scope', 'scope_id'], unique=False, schema='mlops')
    op.create_table('experiments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mlflow_experiment_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('artifact_location', sa.String(length=500), nullable=True),
    sa.Column('lifecycle_stage', sa.Enum('active', 'deleted', name='mlops_experiment_lifecycle'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlflow_experiment_id'),
    schema='mlops'
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('image', 'tabular', 'text', 'audio', 'video', 'custom', name='mlops_dataset_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('dvc_profile_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('dvc_repo_url', sa.String(length=500), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'deprecated', name='mlops_dataset_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dvc_profile_id'], ['mlops.dvc_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='mlops'
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('dvc_md5', sa.String(length=64), nullable=True),
    sa.Column('dvc_commit', sa.String(length=40), nullable=True),
    sa.Column('dvc_profile_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('git_tag', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('schema_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('split_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('metadata_uri', sa.String(length=500), nullable=True),
    sa.Column('validation_report_uri', sa.String(length=500), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=True),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'deprecated', name='mlops_dataset_version_status'), server_default='draft', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['mlops.datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dvc_profile_id'], ['mlops.dvc_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_mlops_dataset_versions_dataset_version'),
    schema='mlops'
    )
    op.create_index('ix_mlops_dataset_versions_dvc_commit', 'dataset_versions', ['dvc_commit'], unique=False, schema='mlops')
    op.create_index('ix_mlops_dataset_versions_dvc_md5', 'dataset_versions', ['dvc_md5'], unique=False, schema='mlops')
    op.create_table('runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.String(length=20), nullable=True),
    sa.Column('runtime_session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SCHEDULED', 'FINISHED', 'FAILED', 'KILLED', name='mlops_run_status'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('NOTEBOOK', 'JOB', 'PROJECT', 'LOCAL', 'UNKNOWN', name='mlops_run_source_type'), nullable=True),
    sa.Column('source_name', sa.String(length=500), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dvc_dataset_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('dvc_md5', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dvc_dataset_version_id'], ['mlops.dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['mlops.experiments.id'], ),
    sa.ForeignKeyConstraint(['runtime_session_id'], ['external_runtime_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlflow_run_id'),
    schema='mlops'
    )
    op.create_index('ix_mlops_runs_dvc_dataset_version_id', 'runs', ['dvc_dataset_version_id'], unique=False, schema='mlops')
    op.create_table('workspace_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=20), nullable=False),
    sa.Column('dataset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mount_path', sa.String(length=255), nullable=False),
    sa.Column('mounted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['mlops.dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_datasets_dataset_id', 'workspace_datasets', ['dataset_id'], unique=False)
    op.create_index('ix_workspace_datasets_workspace_id', 'workspace_datasets', ['workspace_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mlflow_name', sa.String(length=255), nullable=False),
    sa.Column('mlflow_version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('None', 'Staging', 'Production', 'Archived', name='mlops_model_stage'), server_default='None', nullable=False),
    sa.Column('status', sa.Enum('PENDING_REGISTRATION', 'READY', 'FAILED', name='mlops_model_status'), server_default='PENDING_REGISTRATION', nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(stage <> 'Production') OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)", name='ck_mlops_model_versions_prod_requires_approval'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['mlops.runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlflow_name', 'mlflow_version', name='uq_mlops_model_versions_mlflow_name_version'),
    schema='mlops'
    )
    op.create_index('ix_mlops_model_versions_stage', 'model_versions', ['stage'], unique=False, schema='mlops')
    op.create_table('run_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('runtime_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['mlops.runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runtime_session_id'], ['external_runtime_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mlops'
    )
    op.create_index('ix_mlops_run_logs_run_created', 'run_logs', ['run_id', 'created_at'], unique=False, schema='mlops')
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_stage', sa.Enum('Staging', 'Production', name='mlops_approval_target_stage'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='mlops_approval_status'), server_default='pending', nullable=False),
    sa.Column('reviewer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['mlops.model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mlops'
    )
    op.create_index('ix_mlops_approval_requests_model_version_status', 'approval_requests', ['model_version_id', 'status'], unique=False, schema='mlops')
    op.create_table('model_dataset_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('link_type', sa.Enum('train', 'val', 'test', 'eval', name='mlops_link_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['mlops.dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['mlops.model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'dataset_version_id', 'link_type', name='uq_mlops_model_dataset_links_model_dataset_type'),
    schema='mlops'
    )
    op.create_table('workspace_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mount_path', sa.String(length=255), nullable=False),
    sa.Column('mounted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['mlops.model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_models_model_id', 'workspace_models', ['model_id'], unique=False)
    op.create_index('ix_workspace_models_workspace_id', 'workspace_models', ['workspace_id'], unique=False)
    op.drop_index('index_inputs_destination_type_destination_id_source_type', table_name='inputs')
    op.drop_index('index_inputs_input_uuid', table_name='inputs')
    op.drop_table('inputs')
    op.drop_table('input_tags')
    op.drop_index('index_trace_request_metadata_request_id', table_name='trace_request_metadata')
    op.drop_table('trace_request_metadata')
    op.drop_index('index_trace_info_experiment_id_timestamp_ms', table_name='trace_info')
    op.drop_table('trace_info')
    op.drop_index('index_trace_tags_request_id', table_name='trace_tags')
    op.drop_table('trace_tags')
    op.drop_table('alembic_version')
    op.drop_table('storage_providers')
    op.drop_table('model_version_tags')
    op.drop_table('runs')
    op.drop_index('index_tags_run_uuid', table_name='tags')
    op.drop_table('tags')
    op.drop_table('experiment_tags')
    op.drop_index('index_latest_metrics_run_uuid', table_name='latest_metrics')
    op.drop_table('latest_metrics')
    op.drop_table('registered_model_aliases')
    op.drop_index('index_datasets_dataset_uuid', table_name='datasets')
    op.drop_index('index_datasets_experiment_id_dataset_source_type', table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('model_versions')
    op.drop_index('index_metrics_run_uuid', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('index_params_run_uuid', table_name='params')
    op.drop_table('params')
    op.drop_table('registered_model_tags')
    op.drop_table('experiments')
    op.drop_table('registered_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_models',
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='registered_model_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('experiments',
    sa.Column('experiment_id', sa.INTEGER(), server_default=sa.text("nextval('experiments_experiment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('artifact_location', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name='experiments_lifecycle_stage'),
    sa.PrimaryKeyConstraint('experiment_id', name='experiment_pk'),
    sa.UniqueConstraint('name', name='experiments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('registered_model_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name='registered_model_tags_name_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'name', name='registered_model_tag_pk')
    )
    op.create_table('params',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='params_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name='param_pk')
    )
    op.create_index('index_params_run_uuid', 'params', ['run_uuid'], unique=False)
    op.create_table('metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('step', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('is_nan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='metrics_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'timestamp', 'step', 'run_uuid', 'value', 'is_nan', name='metric_pk')
    )
    op.create_index('index_metrics_run_uuid', 'metrics', ['run_uuid'], unique=False)
    op.create_table('model_versions',
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('run_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name='model_versions_name_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'version', name='model_version_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('datasets',
    sa.Column('dataset_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('digest', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dataset_schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dataset_profile', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='datasets_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('experiment_id', 'name', 'digest', name='dataset_pk')
    )
    op.create_index('index_datasets_experiment_id_dataset_source_type', 'datasets', ['experiment_id', 'dataset_source_type'], unique=False)
    op.create_index('index_datasets_dataset_uuid', 'datasets', ['dataset_uuid'], unique=False)
    op.create_table('registered_model_aliases',
    sa.Column('alias', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name='registered_model_alias_name_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'alias', name='registered_model_alias_pk')
    )
    op.create_table('latest_metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('step', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_nan', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='latest_metrics_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name='latest_metric_pk')
    )
    op.create_index('index_latest_metrics_run_uuid', 'latest_metrics', ['run_uuid'], unique=False)
    op.create_table('experiment_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='experiment_tags_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('key', 'experiment_id', name='experiment_tag_pk')
    )
    op.create_table('tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name='tags_run_uuid_fkey'),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name='tag_pk')
    )
    op.create_index('index_tags_run_uuid', 'tags', ['run_uuid'], unique=False)
    op.create_table('runs',
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('entry_point_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('artifact_uri', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name='runs_lifecycle_stage'),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['NOTEBOOK'::character varying, 'JOB'::character varying, 'LOCAL'::character varying, 'UNKNOWN'::character varying, 'PROJECT'::character varying]::text[])", name='source_type'),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'FAILED'::character varying, 'FINISHED'::character varying, 'RUNNING'::character varying, 'KILLED'::character varying]::text[])", name='runs_status_check'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='runs_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('run_uuid', name='run_pk')
    )
    op.create_table('model_version_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name', 'version'], ['model_versions.name', 'model_versions.version'], name='model_version_tags_name_version_fkey', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'name', 'version', name='model_version_tag_pk')
    )
    op.create_table('storage_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('minio', 's3', 'gdrive', name='storage_provider_type'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='storage_providers_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='storage_providers_pkey'),
    sa.UniqueConstraint('name', name='storage_providers_name_key')
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('trace_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name='fk_trace_tags_request_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'request_id', name='trace_tag_pk')
    )
    op.create_index('index_trace_tags_request_id', 'trace_tags', ['request_id'], unique=False)
    op.create_table('trace_info',
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('execution_time_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name='fk_trace_info_experiment_id'),
    sa.PrimaryKeyConstraint('request_id', name='trace_info_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_index('index_trace_info_experiment_id_timestamp_ms', 'trace_info', ['experiment_id', 'timestamp_ms'], unique=False)
    op.create_table('trace_request_metadata',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name='fk_trace_request_metadata_request_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'request_id', name='trace_request_metadata_pk')
    )
    op.create_index('index_trace_request_metadata_request_id', 'trace_request_metadata', ['request_id'], unique=False)
    op.create_table('input_tags',
    sa.Column('input_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('input_uuid', 'name', name='input_tags_pk')
    )
    op.create_table('inputs',
    sa.Column('input_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('source_type', 'source_id', 'destination_type', 'destination_id', name='inputs_pk')
    )
    op.create_index('index_inputs_input_uuid', 'inputs', ['input_uuid'], unique=False)
    op.create_index('index_inputs_destination_type_destination_id_source_type', 'inputs', ['destination_type', 'destination_id', 'source_type'], unique=False)
    op.drop_index('ix_workspace_models_workspace_id', table_name='workspace_models')
    op.drop_index('ix_workspace_models_model_id', table_name='workspace_models')
    op.drop_table('workspace_models')
    op.drop_table('model_dataset_links', schema='mlops')
    op.drop_index('ix_mlops_approval_requests_model_version_status', table_name='approval_requests', schema='mlops')
    op.drop_table('approval_requests', schema='mlops')
    op.drop_index('ix_mlops_run_logs_run_created', table_name='run_logs', schema='mlops')
    op.drop_table('run_logs', schema='mlops')
    op.drop_index('ix_mlops_model_versions_stage', table_name='model_versions', schema='mlops')
    op.drop_table('model_versions', schema='mlops')
    op.drop_index('ix_workspace_datasets_workspace_id', table_name='workspace_datasets')
    op.drop_index('ix_workspace_datasets_dataset_id', table_name='workspace_datasets')
    op.drop_table('workspace_datasets')
    op.drop_index('ix_mlops_runs_dvc_dataset_version_id', table_name='runs', schema='mlops')
    op.drop_table('runs', schema='mlops')
    op.drop_index('ix_mlops_dataset_versions_dvc_md5', table_name='dataset_versions', schema='mlops')
    op.drop_index('ix_mlops_dataset_versions_dvc_commit', table_name='dataset_versions', schema='mlops')
    op.drop_table('dataset_versions', schema='mlops')
    op.drop_table('datasets', schema='mlops')
    op.drop_table('experiments', schema='mlops')
    op.drop_index('ix_mlops_dvc_profiles_scope', table_name='dvc_profiles', schema='mlops')
    op.drop_table('dvc_profiles', schema='mlops')
    op.drop_index('ix_mlops_audit_logs_entity_entity_id_created', table_name='audit_logs', schema='mlops')
    op.drop_table('audit_logs', schema='mlops')
    # ### end Alembic commands ###
